### PR TITLE
popup window with cardinality complete

### PR DESCRIPTION
**Pull request by wanghungjen**
Screenshot 2023-11-14 at 6 01 30 PM

Popup window with cardinality complete! Should work with more than one edges as well

### CODE REVIEW

**Comment by jyyy03** [comment]
Great work! But can you make a background (white should suffice) for the text box to avoid overlapping with the edge itself?

**Comment by wanghungjen** [comment]
Screenshot 2023-11-15 at 10 04 02 AM

Thank you! Yeah! White background complete :)

**Review by jyyy03 — APPROVED** [review]
LGTM!

**Comment by mingchao-zhang** [comment]
Looks good to me. I'm gonna merge this PR, but could you create another PR to change the style of the white box? Maybe make it look as good as the `OWNS` box with a different color and with corners rounded?

**Pull request merged**
